### ISSUE TITLE
Only User Can Delete Their Own Books

### ISSUE THREAD

**Issue by vishal0316** [vishal0316/elib-dashboard#1]
Currently, the application allows users to delete any book in the library. To enhance security and user experience, we need to implement a feature where only the user who uploaded a book can delete it.

**Steps to Reproduce**
User A uploads a book.
User B tries to delete the book uploaded by User A.
The system should prevent User B from deleting the book and display an error message.

**Expected Behavior**
Only the user who uploaded the book should see the delete option.
If another user attempts to delete the book (e.g., via direct API call), the backend should reject the request with a 403 Forbidden status.

**Comment by kaifkh20** [comment]
Attach each book with a user-id should solve

**Comment by kaifkh20** [comment]
Attaching each book with the id of user should solve the problem.

**Comment by vishal0316** [comment]
> Attaching each book with the id of user should solve the problem.

you can try.
